import TopBar from "@/components/TopBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import {
  ProviderConfig,
  ProviderConfigTheme,
} from "@/components/context-provider/provider";
import { useState } from "react";
import Menu from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ProviderConfigTheme>
          <ProviderConfig>
            <TopBar />
            <div className="w-full h-[100vh] pt-20 box-border">
              <Menu />
              <div>{children}</div>
            </div>
          </ProviderConfig>
        </ProviderConfigTheme>
      </body>
    </html>
  );
}
