import TopBar from "@/components/TopBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./layout.scss";
import { ProviderConfigTheme } from "@/components/context-provider/hooks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderConfigTheme>
          <TopBar />
          <main>{children}</main>
        </ProviderConfigTheme>
      </body>
    </html>
  );
}
